### ISSUE TITLE
Unknown reason for test tool exception

### ISSUE THREAD

**Issue by janemiceli** [rabbitmq/rabbitmq-perf-html#1]
I have a cluster of 3 rmq nodes and I am running the follow spec file:

``` json
[{ 'uri':'amqps://user:pass@server:5671', 'name': 'consume', 'type': 'simple', 'params':
[{'time-limit': 60, 'producer-count': 1, 'consumer-count': 1}]}]
```

via command 

```
sudo ./runjava.sh com.rabbitmq.examples.PerfTestMulti spec.js result.js
```

which runs just fine. When I move these numbers up in the spec file:

``` json
[{ 'uri':'amqps://user:pass@server:5671', 'name': 'consume', 'type': 'simple', 'params':
[{'time-limit': 60, 'producer-count': 10, 'consumer-count': 10}]}]
```

I get a stack traces:

```
`ubuntu@i:~/rabbitmq-java-client/build/dist$ sudo ./runjava.sh com.rabbitmq.examples.PerfTestMulti spec.js result.js
Running scenario 'consume' Exception in thread "main" com.rabbitmq.client.ShutdownSignalException: connection error
        at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67)
        at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:37)
        at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:354)
        at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:843)
        at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:765)
        at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:751)
        at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:744)
        at com.rabbitmq.examples.perf.MulticastSet.run(MulticastSet.java:89)
        at com.rabbitmq.examples.perf.MulticastSet.run(MulticastSet.java:45)
        at com.rabbitmq.examples.perf.SimpleScenario.run(SimpleScenario.java:46)
        at com.rabbitmq.examples.PerfTestMulti.runTests(PerfTestMulti.java:97)
        at com.rabbitmq.examples.PerfTestMulti.runStaticBrokerTests(PerfTestMulti.java:91)
        at com.rabbitmq.examples.PerfTestMulti.main(PerfTestMulti.java:64)
Caused by: java.io.EOFException
        at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290)
        at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:95)
        at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:139)
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:534)
        at java.lang.Thread.run(Thread.java:745)`
```

which from what I can tell isn't ulimit, memory or cpu usage. I've run into it on two different test nodes in ec2 (m3 medium and t2 medium) and have reproduced the exact same results:

| consumer | producer | result.spec written out |
| --- | --- | --- |
| 3 | 1 | yes |
| 3 | 2 | yes |
| 3 | 3 | yes |
| 3 | 4 | yes |
| 3 | 5 | yes |
| 3 | 6 | yes |
| 3 | 7 | yes |
| 3 | 8 | yes |
| 3 | 9 | yes |
| 3 | 10 | yes |
| 3 | 11 | yes |
| 3 | 12 | yes |
| 3 | 13 | not written -  stack trace |
| 3 | 14 | not written -  stack trace |
| 4 | 10 | not written -  stack trace |
| 13 | 3 | not written -  stack trace |
| 10 | 10 | not written -  stack trace |

Please let me know if I have something misconfigured, or if this is issue I can help with by giving you more information.

**Comment by videlalvaro** [comment]
Any logs on the rabbitmq nodes from when this happens?

**Comment by janemiceli** [comment]
This is what I get with a tail on one of the nodes when running my test. I don't know use rabbitmq, so I am not sure if it's related:

```
ubuntu@ec2-54-152-203-105:~$ tail -F /var/log/rabbitmq/rabbit@ec2-node.log
=WARNING REPORT==== 26-Feb-2015::01:08:22 ===
closing AMQP connection <0.10090.2> (127.0.0.1:42253 -> 127.0.0.1:5672):
connection_closed_abruptly

=INFO REPORT==== 26-Feb-2015::01:09:22 ===
accepting AMQP connection <0.10100.2> (127.0.0.1:42258 -> 127.0.0.1:5672)

=WARNING REPORT==== 26-Feb-2015::01:09:22 ===
closing AMQP connection <0.10100.2> (127.0.0.1:42258 -> 127.0.0.1:5672):
connection_closed_abruptly

=INFO REPORT==== 26-Feb-2015::01:10:22 ===
accepting AMQP connection <0.10109.2> (127.0.0.1:42264 -> 127.0.0.1:5672)

=WARNING REPORT==== 26-Feb-2015::01:10:22 ===
closing AMQP connection <0.10109.2> (127.0.0.1:42264 -> 127.0.0.1:5672):
connection_closed_abruptly

=INFO REPORT==== 26-Feb-2015::01:11:23 ===
accepting AMQP connection <0.10118.2> (127.0.0.1:42269 -> 127.0.0.1:5672)

=WARNING REPORT==== 26-Feb-2015::01:11:23 ===
closing AMQP connection <0.10118.2> (127.0.0.1:42269 -> 127.0.0.1:5672):
connection_closed_abruptly

=INFO REPORT==== 26-Feb-2015::01:12:22 ===
accepting AMQP connection <0.10127.2> (127.0.0.1:42275 -> 127.0.0.1:5672)

=WARNING REPORT==== 26-Feb-2015::01:12:22 ===
closing AMQP connection <0.10127.2> (127.0.0.1:42275 -> 127.0.0.1:5672):
connection_closed_abruptly

=INFO REPORT==== 26-Feb-2015::01:13:23 ===
accepting AMQP connection <0.10140.2> (127.0.0.1:42280 -> 127.0.0.1:5672)

=WARNING REPORT==== 26-Feb-2015::01:13:23 ===
closing AMQP connection <0.10140.2> (127.0.0.1:42280 -> 127.0.0.1:5672):
connection_closed_abruptly
```

**Comment by michaelklishin** [comment]
Something closes TCP connections mid-test.

If `server` is a remote machine, check for possible intermediaries (proxies, firewalls, load balancers) that may do that. It also may be a good idea to check local and remote syslog.

**Comment by michaelklishin** [comment]
This is something environment-specific. Please ask questions on rabbitmq-users.
